dist: bionic
addons:
  postgresql: "10"
  apt:
    packages:
     - postgresql-10-postgis-2.4
language: python
sudo: false
cache: pip
python:
 - "3.8-dev"
 - "3.7"
 - "3.6"
 - "3.5"
install: pip install tox-travis coverage coveralls
script: tox
after_success:
 - coveralls
